const dataProblems = [
    {
        problemId: 100,
        problemTitle: "Broken Fan",
        problemDescription: "The ceiling fan in room 203 is not working properly and making unusual noise",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 101,
        roomNumber: 203,
        hostel: "BH-1",
        category: "Electrical",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-01-05T09:30:00",
        timeResolved: ""
    },
    {
        problemId: 102,
        problemTitle: "Water Leakage",
        problemDescription: "There is continuous water leakage from bathroom pipe causing water logging",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 102,
        roomNumber: 204,
        hostel: "BH-2",
        category: "Plumbing",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-01-10T14:20:00",
        timeResolved: "2025-01-12T11:45:00"
    },
    {
        problemId: 103,
        problemTitle: "Broken Chair",
        problemDescription: "The study chair in room 405 is broken and needs immediate replacement",
        problemImage: "/images/furnitureProblem.jpg",
        studentId: 103,
        roomNumber: 405,
        hostel: "BH-3",
        category: "Furniture",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-01-15T16:45:00",
        timeResolved: ""
    },
    {
        problemId: 104,
        problemTitle: "WiFi Issues",
        problemDescription: "No internet connectivity in the entire 2nd floor since morning",
        problemImage: "/images/internetProblem.jpg",
        studentId: 104,
        roomNumber: 205,
        hostel: "BH-4",
        category: "Internet",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-01-20T08:15:00",
        timeResolved: ""
    },
    {
        problemId: 105,
        problemTitle: "Paint Peeling",
        problemDescription: "The wall paint in room 302 is peeling off due to moisture",
        problemImage: "/images/paintingProblem.jpg",
        studentId: 105,
        roomNumber: 302,
        hostel: "BH-1",
        category: "Painting",
        status: "Rejected",
        studentStatus: "NotResolved",
        timeCreated: "2025-01-25T11:30:00",
        timeResolved: "2025-01-26T09:20:00"
    },
    {
        problemId: 106,
        problemTitle: "Clogged Drain",
        problemDescription: "Bathroom drain is completely clogged causing water to overflow",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 106,
        roomNumber: 210,
        hostel: "BH-2",
        category: "Plumbing",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-01-30T13:45:00",
        timeResolved: ""
    },
    {
        problemId: 107,
        problemTitle: "Broken Window",
        problemDescription: "Window glass is cracked and needs replacement before monsoon",
        problemImage: "/images/carpentryProblem.jpg",
        studentId: 107,
        roomNumber: 315,
        hostel: "BH-3",
        category: "Carpentry",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-02-01T10:20:00",
        timeResolved: "2025-02-03T15:30:00"
    },
    {
        problemId: 108,
        problemTitle: "AC Not Cooling",
        problemDescription: "Air conditioner in common room is running but not cooling properly",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 108,
        roomNumber: 101,
        hostel: "BH-4",
        category: "Electrical",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-02-05T09:10:00",
        timeResolved: ""
    },
    {
        problemId: 109,
        problemTitle: "Bed Bug Infestation",
        problemDescription: "Severe bed bug infestation in mattress requiring urgent pest control",
        problemImage: "/images/pestProblem.jpg",
        studentId: 109,
        roomNumber: 412,
        hostel: "BH-1",
        category: "Pest Control",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-02-10T14:30:00",
        timeResolved: "2025-02-12T11:15:00"
    },
    {
        problemId: 110,
        problemTitle: "Faulty Door Lock",
        problemDescription: "Room door lock is broken and cannot be secured properly",
        problemImage: "/images/carpentryProblem.jpg",
        studentId: 110,
        roomNumber: 208,
        hostel: "BH-2",
        category: "Carpentry",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-02-15T16:20:00",
        timeResolved: ""
    },
    {
        problemId: 111,
        problemTitle: "Flickering Lights",
        problemDescription: "Lights in study area are constantly flickering causing eye strain",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 111,
        roomNumber: 305,
        hostel: "BH-3",
        category: "Electrical",
        status: "Rejected",
        studentStatus: "NotResolved",
        timeCreated: "2025-02-20T08:45:00",
        timeResolved: "2025-02-21T10:30:00"
    },
    {
        problemId: 112,
        problemTitle: "Heating Issue",
        problemDescription: "Room heater not functioning during cold weather",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 112,
        roomNumber: 401,
        hostel: "BH-4",
        category: "Electrical",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-02-25T12:15:00",
        timeResolved: "2025-02-27T09:45:00"
    },
    {
        problemId: 113,
        problemTitle: "Leaking Roof",
        problemDescription: "Water dripping from ceiling during rain causing damage to belongings",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 113,
        roomNumber: 506,
        hostel: "BH-1",
        category: "Plumbing",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-01T07:30:00",
        timeResolved: ""
    },
    {
        problemId: 114,
        problemTitle: "Broken Cupboard",
        problemDescription: "Cupboard door hinges are broken and door is falling off",
        problemImage: "/images/furnitureProblem.jpg",
        studentId: 114,
        roomNumber: 215,
        hostel: "BH-2",
        category: "Furniture",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-05T15:40:00",
        timeResolved: "2025-03-07T13:20:00"
    },
    {
        problemId: 115,
        problemTitle: "Toilet Flush Not Working",
        problemDescription: "Toilet flush mechanism is broken and needs replacement",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 115,
        roomNumber: 318,
        hostel: "BH-3",
        category: "Plumbing",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-08T10:50:00",
        timeResolved: ""
    },
    {
        problemId: 116,
        problemTitle: "Noisy Neighbors",
        problemDescription: "Excessive noise from adjacent room during study hours",
        problemImage: "/images/otherProblem.jpg",
        studentId: 116,
        roomNumber: 402,
        hostel: "BH-4",
        category: "Other",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-10T19:25:00",
        timeResolved: "2025-03-12T14:10:00"
    },
    {
        problemId: 117,
        problemTitle: "Broken Shower Head",
        problemDescription: "Shower head is cracked and spraying water in all directions",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 117,
        roomNumber: 507,
        hostel: "BH-1",
        category: "Plumbing",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-13T08:35:00",
        timeResolved: ""
    },
    {
        problemId: 118,
        problemTitle: "Missing Dustbin",
        problemDescription: "Room dustbin has been missing since cleaning staff visit",
        problemImage: "/images/cleaningProblem.jpg",
        studentId: 118,
        roomNumber: 220,
        hostel: "BH-2",
        category: "Cleaning",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-15T11:15:00",
        timeResolved: "2025-03-16T09:30:00"
    },
    {
        problemId: 119,
        problemTitle: "Faulty Electrical Socket",
        problemDescription: "Wall socket is loose and causing sparks when plugged in",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 119,
        roomNumber: 325,
        hostel: "BH-3",
        category: "Electrical",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-17T14:50:00",
        timeResolved: ""
    },
    {
        problemId: 120,
        problemTitle: "Broken Study Table",
        problemDescription: "Study table leg is broken making it unstable and unusable",
        problemImage: "/images/furnitureProblem.jpg",
        studentId: 120,
        roomNumber: 410,
        hostel: "BH-4",
        category: "Furniture",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-18T16:40:00",
        timeResolved: "2025-03-20T13:25:00"
    },
    {
        problemId: 121,
        problemTitle: "Mosquito Infestation",
        problemDescription: "Severe mosquito problem in room despite using repellents",
        problemImage: "/images/pestProblem.jpg",
        studentId: 121,
        roomNumber: 510,
        hostel: "BH-1",
        category: "Pest Control",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-19T09:20:00",
        timeResolved: ""
    },
    {
        problemId: 122,
        problemTitle: "Dirty Water Supply",
        problemDescription: "Tap water is coming brown and dirty since yesterday",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 122,
        roomNumber: 225,
        hostel: "BH-2",
        category: "Plumbing",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-20T07:30:00",
        timeResolved: "2025-03-21T16:45:00"
    },
    {
        problemId: 123,
        problemTitle: "Broken Mirror",
        problemDescription: "Bathroom mirror is cracked and pieces are falling off",
        problemImage: "/images/furnitureProblem.jpg",
        studentId: 123,
        roomNumber: 330,
        hostel: "BH-3",
        category: "Furniture",
        status: "Rejected",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-21T13:10:00",
        timeResolved: "2025-03-22T10:20:00"
    },
    {
        problemId: 124,
        problemTitle: "No Hot Water",
        problemDescription: "Hot water geyser not working in bathroom during winter",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 124,
        roomNumber: 415,
        hostel: "BH-4",
        category: "Electrical",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-22T08:50:00",
        timeResolved: ""
    },
    {
        problemId: 125,
        problemTitle: "Damaged Ceiling",
        problemDescription: "Ceiling plaster is falling off in chunks creating mess and hazard",
        problemImage: "/images/paintingProblem.jpg",
        studentId: 125,
        roomNumber: 515,
        hostel: "BH-1",
        category: "Painting",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-23T11:25:00",
        timeResolved: "2025-03-24T14:30:00"
    },
    {
        problemId: 126,
        problemTitle: "Slow Drainage",
        problemDescription: "Sink drains very slowly causing water to accumulate",
        problemImage: "/images/plumbingProblem.jpg",
        studentId: 126,
        roomNumber: 230,
        hostel: "BH-2",
        category: "Plumbing",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-24T15:40:00",
        timeResolved: ""
    },
    {
        problemId: 127,
        problemTitle: "Faulty Room Lights",
        problemDescription: "Main room light not turning on despite changing bulb",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 127,
        roomNumber: 335,
        hostel: "BH-3",
        category: "Electrical",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-24T09:15:00",
        timeResolved: "2025-03-25T12:30:00"
    },
    {
        problemId: 128,
        problemTitle: "Broken Bed Frame",
        problemDescription: "Bed frame has collapsed on one side making it difficult to sleep",
        problemImage: "/images/furnitureProblem.jpg",
        studentId: 128,
        roomNumber: 420,
        hostel: "BH-4",
        category: "Furniture",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-25T17:20:00",
        timeResolved: ""
    },
    {
        problemId: 129,
        problemTitle: "Mold Growth",
        problemDescription: "Black mold growing on bathroom walls causing health concerns",
        problemImage: "/images/cleaningProblem.jpg",
        studentId: 129,
        roomNumber: 520,
        hostel: "BH-1",
        category: "Cleaning",
        status: "Resolved",
        studentStatus: "Resolved",
        timeCreated: "2025-03-25T10:35:00",
        timeResolved: "2025-03-25T11:45:00"
    },
    {
        problemId: 130,
        problemTitle: "Heating Issue in Common Room",
        problemDescription: "The heating system in the common room is not functioning properly.",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 101,
        roomNumber: 203,
        hostel: "BH-1",
        category: "Electrical",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-26T10:00:00",
        timeResolved: ""
    },
    {
        problemId: 131,
        problemTitle: "Broken Light Switch",
        problemDescription: "The light switch in room 203 is not working.",
        problemImage: "/images/electricalProblem.jpg",
        studentId: 101,
        roomNumber: 203,
        hostel: "BH-1",
        category: "Electrical",
        status: "Pending",
        studentStatus: "NotResolved",
        timeCreated: "2025-03-27T11:00:00",
        timeResolved: ""
    }
];

const dataEntryExit = [
    {
        transitId: 1,
        studentRollNumber: 101,
        studentName: "John Doe",
        studentHostel: "BH-2",
        studentRoomNumber: 203,
        purpose: "going to home",
        transitStatus: "ENTRY",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 2,
        studentRollNumber: 102,
        studentName: "Jane Doe",
        studentHostel: "BH-1",
        studentRoomNumber: 204,
        purpose: "coming back to hostel",
        transitStatus: "EXIT",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 3,
        studentRollNumber: 103,
        studentName: "Vikas",
        studentHostel: "BH-1",
        studentRoomNumber: 203,
        purpose: "going to chennai",
        transitStatus: "ENTRY",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 4,
        studentRollNumber: 104,
        studentName: "Raj",
        studentHostel: "BH-1",
        studentRoomNumber: 204,
        purpose: "coming back to hostel",
        transitStatus: "EXIT",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 5,
        studentRollNumber: 183,
        studentName: "Rajesh",
        studentHostel: "BH-1",
        studentRoomNumber: 423,
        purpose: "going to sullurpeta",
        transitStatus: "EXIT",
        date: "2025-03-14",
        time: "08:30:00",
    }
];


const userData = [
    {
        userId: "101",
        name: "John Doe",
        hostel: "BH-1",
        roomNo: 203,
        year: "UG-1",
        email: "john.doe@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 101,
        feeStatus: {
            hostelFees: false,
            messFees: true
        }
    },
    {
        userId: "102",
        name: "Jane Doe",
        hostel: "BH-2",
        roomNo: 204,
        year: "UG-2",
        email: "jane.doe@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 102,
        feeStatus: {
            hostelFees: true,
            messFees: true
        }
    },
    {
        userId: "103",
        name: "Vikas",
        hostel: "BH-1",
        roomNo: 203,
        year: "UG-1",
        email: "vikas@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 103,
        feeStatus: {
            hostelFees: false,
            messFees: false
        }
    },
    {
        userId: "104",
        name: "Raj",
        hostel: "BH-1",
        roomNo: 204,
        year: "UG-2",
        email: "raj@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 104,
        feeStatus: {
            hostelFees: true,
            messFees: false
        }
    },
    {
        userId: "105",
        name: "Pratyush",
        hostel: "BH-1",
        roomNo: 203,
        year: "UG-1",
        email: "pratyush@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 105,
        feeStatus: {
            hostelFees: true,
            messFees: true
        }
    },
    {
        userId: "106",
        name: "Admin",
        email: "admin@gmail.com",
        password: "password123",
        role: "admin",
        feeStatus: {
            hostelFees: false,
            messFees: false
        }
    },
    {
        userId: "107",
        name: "Warden1",
        email: "warden1@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-1",
        feeStatus: {
            hostelFees: false,
            messFees: false
        }
    },
    {
        userId: "108",
        name: "Warden2",
        email: "warden2@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-2",
        feeStatus: {
            hostelFees: false,
            messFees: false
        }
    },
    {
        userId: "109",
        name: "Warden3",
        email: "warden3@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-3",
        feeStatus: {
            hostelFees: false,
            messFees: false
        }
    },
    {
        userId: "110",
        name: "Warden4",
        email: "warden4@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-4",
        feeStatus: {
            hostelFees: false,
            messFees: false
        }
    }
]

module.exports = { dataProblems, dataEntryExit, userData };
