const dataProblems = [
    {
        problemId: 100,
        problemTitle: "Broken Fan cutiya",
        problemDescription: "The ceiling fan in room 203 is not working properly and making unusual noise",
        problemImage: "/uploads/1716633600421-fan.jpg",
        studentId: 101,
        roomNumber: 203,
        hostel: "BH-1",
        category: "Electrical",
        status: "Pending"
    },
    {
        problemId: 102,
        problemTitle: "Water Leakage",
        problemDescription: "There is continuous water leakage from bathroom pipe causing water logging",
        problemImage: "/uploads/1716633600421-water.jpg",
        studentId: 102,
        roomNumber: 204,
        hostel: "BH-2",
        category: "Plumbing",
        status: "Resolved"
    },
    {
        problemId: 103,
        problemTitle: "Broken Chair",
        problemDescription: "The study chair in room 405 is broken and needs immediate replacement",
        problemImage: "/uploads/1716633600421-chair.jpg",
        studentId: 103,
        roomNumber: 405,
        hostel: "BH-3",
        category: "Furniture",
        status: "Pending"
    },
    {
        problemId: 104,
        problemTitle: "WiFi Issues",
        problemDescription: "No internet connectivity in the entire 2nd floor since morning",
        problemImage: "/uploads/1716633600421-wifi.jpg",
        studentId: 104,
        roomNumber: 205,
        hostel: "BH-4",
        category: "Internet",
        status: "Pending"
    },
    {
        problemId: 105,
        problemTitle: "Paint Peeling",
        problemDescription: "The wall paint in room 302 is peeling off due to moisture",
        problemImage: "/uploads/1716633600421-paint.jpg",
        studentId: 105,
        roomNumber: 302,
        hostel: "BH-1",
        category: "Painting",
        status: "Rejected"
    }
];

const dataEntryExit = [
    {
        transitId: 1,
        studentRollNumber: 101,
        studentName: "John Doe",
        studentHostel: "BH-2",
        studentRoomNumber: 203,
        purpose: "going to home",
        transitStatus: "ENTRY",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 2,
        studentRollNumber: 102,
        studentName: "Jane Doe",
        studentHostel: "BH-1",
        studentRoomNumber: 204,
        purpose: "coming back to hostel",
        transitStatus: "EXIT",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 3,
        studentRollNumber: 103,
        studentName: "Vikas",
        studentHostel: "BH-1",
        studentRoomNumber: 203,
        purpose: "going to chennai",
        transitStatus: "ENTRY",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 4,
        studentRollNumber: 104,
        studentName: "Raj",
        studentHostel: "BH-1",
        studentRoomNumber: 204,
        purpose: "coming back to hostel",
        transitStatus: "EXIT",
        date: "2025-03-23",
        time: "10:00:00",
    },
    {
        transitId: 5,
        studentRollNumber: 183,
        studentName: "Pratyush",
        studentHostel: "BH-1",
        studentRoomNumber: 423,
        purpose: "going to sullurpeta",
        transitStatus: "EXIT",
        date: "2025-03-14",
        time: "08:30:00",
    }
];


const userData = [
    {
        userId: "101",
        name: "John Doe",
        hostel: "BH-1",
        roomNo: 203,
        year: "UG-1",
        email: "john.doe@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 101,
    },
    {
        userId: "102",
        name: "Jane Doe",
        hostel: "BH-2",
        roomNo: 204,
        year: "UG-2",
        email: "jane.doe@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 102,
    },
    {
        userId: "103",
        name: "Vikas",
        hostel: "BH-1",
        roomNo: 203,
        year: "UG-1",
        email: "vikas@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 103,
    },
    {
        userId: "104",
        name: "Raj",
        hostel: "BH-1",
        roomNo: 204,
        year: "UG-2",
        email: "raj@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 104,
    },
    {
        userId: "105",
        name: "Pratyush",
        hostel: "BH-1",
        roomNo: 203,
        year: "UG-1",
        email: "pratyush@gmail.com",
        password: "password123",
        role: "student",
        rollNo: 105,
    },
    {
        userId: "106",
        name: "Admin",
        email: "admin@gmail.com",
        password: "password123",
        role: "admin",
    },
    {
        userId: "107",
        name: "Warden1",
        email: "warden1@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-1",
    },
    {
        userId: "108",
        name: "Warden2",
        email: "warden2@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-2",
    },
    {
        userId: "109",
        name: "Warden3",
        email: "warden3@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-3",
    },
    {
        userId: "110",
        name: "Warden4",
        email: "warden4@gmail.com",
        password: "password123",
        role: "warden",
        hostel: "BH-4",
    }
]

module.exports = { dataProblems, dataEntryExit, userData };
